#!/bin/sh
. /etc/profile

if [ ! -d /storage/roms/saves ]
then
    mkdir /storage/roms/saves
    sync
fi

if [ ! -d /storage/roms/savestates ]
then
    mkdir /storage/roms/savestates
    sync
fi

if [ ! -d /storage/roms/storageupdate ]
then
    mkdir /storage/roms/storageupdate
    sync
fi

CONFIG_FILE="/storage/.config/system/configs/system.cfg"
HOSTNAME_LINE="system.hostname=rogue_pixel2"

if [ -f "$CONFIG_FILE" ]; then
    if grep -Fxq "$HOSTNAME_LINE" "$CONFIG_FILE"; then
        echo "This is ROGUE OS."
    else
        poweroff
    fi
fi

cp -f /usr/local/share/emulationstation/es_features.cfg /storage/.config/emulationstation/es_features.cfg
cp -f /usr/local/share/emulationstation/es_systems.cfg /storage/.config/emulationstation/es_systems.cfg
cp -f /usr/local/share/emulationstation/runemu.sh /storage/bin/overlay_usr_bin/runemu.sh

if [ -f /storage/roms/storageupdate/storage.7z ]
then

7za x -y /storage/roms/storageupdate/storage.7z ".deletes" -o/storage

if [ -f /storage/.deletes ]; then
    while IFS= read -r file_to_delete; do
    if [ -f "${file_to_delete}" ]; then
       rm "${file_to_delete}"
    elif [ -d "${file_to_delete}" ]; then
       rm -rf "${file_to_delete}"
    fi
    done < /storage/.deletes
fi

7za x /storage/roms/storageupdate/storage.7z -o/storage -aoa
rm /storage/roms/storageupdate/storage.7z
rm /storage/.deletes
sync

unzip -o /storage/.config/PortMaster/release/PortMaster.zip -d /storage/roms/ports/
sync

if [ -f /storage/roms/storageupdate/runtimes.7z ]; then
7za x /storage/roms/storageupdate/runtimes.7z -o/storage/roms/ports/PortMaster/libs/ -aoa
rm /storage/roms/storageupdate/runtimes.7z
sync
fi

reboot
fi