#!/bin/sh
. /etc/profile

if [ ! -d /storage/roms/saves ]
then
    mkdir /storage/roms/saves
    sync
fi

if [ ! -d /storage/roms/savestates ]
then
    mkdir /storage/roms/savestates
    sync
fi

if [ ! -d /storage/roms/storageupdate ]
then
    mkdir /storage/roms/storageupdate
    sync
fi

if [ ! -f "/storage/.config/gmu/gmu.cfg" ]
then
   cp -f "/usr/config/gmu/gmu.cfg" "/storage/.config/gmu/gmu.cfg"
   sync
fi

if [ ! -f "/storage/.config/gmu/playlists/Start Music Player.sh" ]
then
   mkdir -p "/storage/.config/gmu/playlists"
   cp -f "/usr/config/gmu/playlists/Start Music Player.sh" "/storage/.config/gmu/playlists/Start Music Player.sh"
   sync
fi

if [ ! -f "/storage/.config/gmu/playlists/images/Start Music Player.png" ]
then
   mkdir -p "/storage/.config/gmu/playlists/images"
   cp -f "/usr/config/gmu/playlists/images/Start Music Player.png" "/storage/.config/gmu/playlists/images/Start Music Player.png"
   sync
fi

if [ ! -f "/storage/.config/gmu/playlists/Start Game Music Emulator.sh" ]
then
   mkdir -p "/storage/.config/gmu/playlists"
   cp -f "/usr/config/gmu/playlists/Start Game Music Emulator.sh" "/storage/.config/gmu/playlists/Start Game Music Emulator.sh"
   sync
fi

if [ ! -f "/storage/.config/gmu/playlists/images/Start Game Music Emulator.png" ]
then
   mkdir -p "/storage/.config/gmu/playlists/images"
   cp -f "/usr/config/gmu/playlists/images/Start Game Music Emulator.png" "/storage/.config/gmu/playlists/images/Start Game Music Emulator.png"
   sync
fi

if [ ! -f "/storage/.config/gmu/playlists/Start GSF player.sh" ]
then
   mkdir -p "/storage/.config/gmu/playlists"
   rm -f "/storage/.config/gmu/playlists/Start GFS player.sh"
   cp -f "/usr/config/gmu/playlists/Start GSF player.sh" "/storage/.config/gmu/playlists/Start GSF player.sh"
   sync
fi

if [ ! -f "/storage/.config/gmu/playlists/images/Start GSF player.png" ]
then
   mkdir -p "/storage/.config/gmu/playlists/images"
   cp -f "/usr/config/gmu/playlists/images/Start GSF player.png" "/storage/.config/gmu/playlists/images/Start GSF player.png"
   sync
fi

if [ -f "/storage/.cache/connman/settings" ]
then
   rm "/storage/.cache/connman/settings"
   cp -f "/usr/cache/connman/settings" "/storage/.cache/connman/settings"
   sync
fi

if [ ! -f "/storage/.cache/connman/settings" ]
then
   cp -f "/usr/cache/connman/settings" "/storage/.cache/connman/settings"
   sync
fi

for cfg in /storage/.config/retroarch/retroarch.cfg /tmp/.retroarch.cfg; do
    if [ -f "$cfg" ]; then
        if grep -q '^video_threaded = "true"$' "$cfg"; then
            sed -i 's/^video_threaded = "true"$/video_threaded = "false"/' "$cfg"
            sync
        fi
    fi
done

CONFIG_FILE="/storage/.config/system/configs/system.cfg"
HOSTNAME_LINE="system.hostname=rogue_pixel2"

if [ -f "$CONFIG_FILE" ]; then
    if grep -Fxq "$HOSTNAME_LINE" "$CONFIG_FILE"; then
        echo "This is ROGUE OS."
    else
        poweroff
    fi
fi

set_config_value() {
  local key="$1"
  local value="$2"
  local key_escaped
  key_escaped=$(printf '%s\n' "$key" | sed 's/[][&/\.^$*]/\\&/g')

  if grep -q "$key_escaped" "$CONFIG_FILE"; then
    sed -i "s#.*$key_escaped.*#$key=$value#" "$CONFIG_FILE"
  else
    echo "$key=$value" >> "$CONFIG_FILE"
  fi
}

set_config_value 'music["Start Music Player.sh"].cpugovernor' 'powersave'
set_config_value 'music["Start Music Player.sh"].gpuperf' 'low'
set_config_value 'music["Start Game Music Emulator.sh"].cpugovernor' 'powersave'
set_config_value 'music["Start Game Music Emulator.sh"].gpuperf' 'low'
set_config_value 'music["Start GSF player.sh"].cpugovernor' 'ondemand'
set_config_value 'music["Start GSF player.sh"].gpuperf' 'auto'
set_config_value 'system.power.audio' '1'
set_config_value 'system.power.cpu' '1'
set_config_value 'system.power.pcie' '1'
set_config_value 'system.power.rtpm' '1'
set_config_value 'system.power.wakeevents' '0'
set_config_value 'system.power.wifi' '1'
set_config_value 'system.powersave' '1'
set_config_value 'system.suspendmode' 'mem'

cp -f /usr/local/share/emulationstation/es_features.cfg /storage/.config/emulationstation/es_features.cfg
cp -f /usr/local/share/emulationstation/es_systems.cfg /storage/.config/emulationstation/es_systems.cfg
cp -f /usr/local/share/emulationstation/runemu.sh /storage/bin/overlay_usr_bin/runemu.sh

#set pyxel

if [ ! -f /storage/.local/bin/pyxel ]
then
    cp -r /usr/local/share/pyxel/storage/.* /storage/
    chmod +x /storage/.local/bin/* 2>/dev/null
    chmod +x /storage/.local/lib/* 2>/dev/null
    mkdir /roms/pyxel
    cp -r /usr/local/share/pyxel/storage/.local/lib/python3.11/site-packages/pyxel/examples/* /roms/pyxel/
    sync
    reboot
fi

#upgrade iux

IUX="/storage/iux/thisui"

IUX_HASH="923c630497f5869cbacd1cbf3b67f1539f6b38ae925e2648727049aac4cf9868"

SRC_iux="/usr/local/share/iux/"
DST_iux="/storage/iux/"


if [[ -f "$IUX" ]]; then
    CURRENT_HASH=$(sha256sum "$IUX" | awk '{print $1}')

    if [[ "$CURRENT_HASH" != "$IUX_HASH" ]]; then
        echo "IUX Invalid hash, rewrite files..."
        cp -r "$SRC_iux"* "$DST_iux"
        chmod -R +x "$DST_iux"
        sync
    else
        echo "IUX Correct hast."
    fi
fi

RUNNER_DRASTIC="/storage/drastic/runner"

RUNNER_HASH="80f0861993f78fe4eadc2784950e4ea7af037857f28bd606c9867feebcb3ee6d"

SRC_drastic="/usr/local/share/drastic/"
DST_drastic="/storage/drastic/"


if [[ -f "$RUNNER_DRASTIC" ]]; then
    CURRENT_HASH=$(sha256sum "$RUNNER_DRASTIC" | awk '{print $1}')

    if [[ "$CURRENT_HASH" != "$RUNNER_HASH" ]]; then
        echo "DRASTIC Invalid hash, rewrite files..."
        cp -r "$SRC_drastic"* "$DST_drastic"
        chmod -R +x "$DST_drastic"
        sync
    else
        echo "DRASTIC Correct hast."
    fi
fi

ldconfig
sync

if [ -f /storage/roms/storageupdate/storage.7z ]
then

7za x -y /storage/roms/storageupdate/storage.7z ".deletes" -o/storage

if [ -f /storage/.deletes ]; then
    while IFS= read -r file_to_delete; do
    if [ -f "${file_to_delete}" ]; then
       rm "${file_to_delete}"
    elif [ -d "${file_to_delete}" ]; then
       rm -rf "${file_to_delete}"
    fi
    done < /storage/.deletes
fi

7za x /storage/roms/storageupdate/storage.7z -o/storage -aoa
rm /storage/roms/storageupdate/storage.7z
rm /storage/.deletes
sync

unzip -o /storage/.config/PortMaster/release/PortMaster.zip -d /storage/roms/ports/
sync

if [ -f /storage/roms/storageupdate/runtimes.7z ]; then
7za x /storage/roms/storageupdate/runtimes.7z -o/storage/roms/ports/PortMaster/libs/ -aoa
rm /storage/roms/storageupdate/runtimes.7z
sync
fi

reboot
fi