# gkd350h settings
modifier=keyboard,76
confirm=joystickbutton,0,1
cancel=joystickbutton,0,0
manual=joystickbutton,0,3
dec=keyboard,75
inc=joystickbutton,0,2
section_prev=joystickbutton,0,4
section_next=joystickbutton,0,5
pageup=keyboard,9
pagedown=keyboard,8
menu=joystickbutton,0,8
settings=joystickbutton,0,9
volup=joystickbutton,0,10
voldown=joystickbutton,0,17
up=joystickbutton,0,10
down=joystickbutton,0,11
left=joystickbutton,0,12
right=joystickbutton,0,13
power=keyboard,308

#0=b 1=a 2=x 3=y 4=L1 5=R1 6=L2 7=R2 8=SELECT  9=START
#左边小圆点=10 11=飞机2  12=
#13=UP 14=DOWN 15=LEFT 16=RIGHT
#17=右边小圆点

 4=L1 5=R1 6=L2 7=R2 8=SELECT  9=START
#左边小圆点=10 11=飞机2  12=
#13=UP 14=DOWN 15=LEFT 16=RIGHT
#17=右边小圆点

